name: ðŸ§ª PR checks
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint
  golang_ci_lint_version: v2.7.2
jobs:
  go-tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go 1.x
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: check go deps
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: ${{ env.golang_ci_lint_version }}
          args: --timeout=5m

      - name: make build
        run: make build

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain -- **/crd/*.yaml) ]]; then
            echo "::error::Please commit generated CRDs files"
            git status --porcelain -- **/crd/*.yaml
            exit 1
          fi
        shell: bash

      - name: make test
        run: make test
